# This file was generated by GoReleaser. DO NOT EDIT.
cask "super_hooks" do
  version "0.0.1"

  on_macos do
    on_intel do
      sha256 "5c15d4729220f0978177d5a39ad3ad7d35092caecde906a3589f9b1f16f16f02"
      url "https://github.com/frankywahl/super_hooks/releases/download/v#{version}/super_hooks_#{version}_macOS-64bit.tar.gz"
    end
    on_arm do
      sha256 "d50275ab106f67ad6ff2d4b1b5f3f45466cb3b6f8b2fda34d96a06b036442212"
      url "https://github.com/frankywahl/super_hooks/releases/download/v#{version}/super_hooks_#{version}_macOS-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9873f415471492690ece4a9d854e16008f07407f60d361562c2887c665bfe1c9"
      url "https://github.com/frankywahl/super_hooks/releases/download/v#{version}/super_hooks_#{version}_Linux-64bit.tar.gz"
    end
    on_arm do
      sha256 "4e797e50d0dfcef89271d1e7d99056dbc2647c4ad2c3385fe91eb64322736f9d"
      url "https://github.com/frankywahl/super_hooks/releases/download/v#{version}/super_hooks_#{version}_Linux-arm64.tar.gz"
    end
  end

  name "super_hooks"
  desc "Hooks handling for git"
  homepage "http://github.com/frankywahl/super_hooks"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "super_hooks"

  # No zap stanza required

end
