# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SuperHooks < Formula
  desc "Hooks handling for git"
  homepage "http://github.com/frankywahl/super_hooks"
  version "0.0.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/frankywahl/super_hooks/releases/download/v0.0.1/super_hooks_0.0.1_macOS-64bit.tar.gz"
    sha256 "cc7f9b5c6074f517b9fcfc4a0e4b8b90090b53593ff8d9ab950ea4c4f00fe718"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/frankywahl/super_hooks/releases/download/v0.0.1/super_hooks_0.0.1_Linux-64bit.tar.gz"
    sha256 "e021165dffc89f0062c07cf18e4204afc5a1a9ee56f4ad2bc648856f6fe6f116"
  end

  def install
    bin.install "super_hooks"
  end
end
