# This file was generated by GoReleaser. DO NOT EDIT.
cask "super_hooks" do
  version "0.0.1"

  on_macos do
    on_intel do
      sha256 "e5805b9ebace256c9ad9bbd499f008aa0370d6cb1fc2a2390cee4d3bc12fa33d"
      url "https://github.com/frankywahl/super_hooks/releases/download/v#{version}/super_hooks_#{version}_macOS-64bit.tar.gz"
    end
    on_arm do
      sha256 "12889be579298cd1ecc00f245c7603fc8326eb275834923bbc948a3fbf7e2bc7"
      url "https://github.com/frankywahl/super_hooks/releases/download/v#{version}/super_hooks_#{version}_macOS-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e450e0e37b5d80bdc538644535e73db9fb4f1df45cebe7dd0e6a9b499bc1a7af"
      url "https://github.com/frankywahl/super_hooks/releases/download/v#{version}/super_hooks_#{version}_Linux-64bit.tar.gz"
    end
    on_arm do
      sha256 "d3007681e0fa139fef720aceca4c85436d4aae62c2f8d32bf3782d51ebc8b9b3"
      url "https://github.com/frankywahl/super_hooks/releases/download/v#{version}/super_hooks_#{version}_Linux-arm64.tar.gz"
    end
  end

  name "super_hooks"
  desc "Hooks handling for git"
  homepage "http://github.com/frankywahl/super_hooks"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "super_hooks"

  # No zap stanza required

end
